version: "2.4"
networks:
  net:
services:
  socket1:
    container_name: socket1
    build: .
    environment:
      - SERVER_PORT=3333
      - HTTP_SERVER_PORT=8000
      - TARGET_HOST=socket2
      - TARGET_PORT=4444
      - RESPONSE_DELAY=10000
    ports:
      - 3333:3333
      - 8001:8000
    networks:
      - net
  socket2:
    container_name: socket2
    build: .
    environment:
      - SERVER_PORT=4444
      - HTTP_SERVER_PORT=8000
      - TARGET_HOST=socket1
      - TARGET_PORT=3333
      - INIT_DELAY=5000
      - RESPONSE_DELAY=3000
    ports:
      - 4444:4444
      - 8002:8000
    networks:
      - net